name: swappid
description: "Africa's leading financial services platform"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Dotted Line
  dotted_line: ^3.2.2

  # Dropdown
  dropdown_button2: ^3.0.0-beta.20

  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^17.2.2
  firebase_installations: ^16.3.6

  # animation
  lottie: ^3.1.3
  pulsator: ^1.0.0+2
  animate_do: ^3.3.4
  animations: ^2.0.11
  flutter_animate: ^4.5.2
  circular_rotation: ^0.0.2

  # Hive local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Config keys
  flutter_dotenv: ^5.2.1

  # Indicator
  smooth_page_indicator: ^1.2.0+3

  # State Manager
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0

  # Device Manager
  device_info_plus: ^11.1.1

  # Carousel
  carousel_slider: ^5.0.0

  # Adaptive UI
  flutter_screenutil: ^5.9.3

  #UI
  shimmer: ^3.0.0

  # OTP
  timer_count_down: ^2.2.2

  # Share
  share_plus: ^10.1.4

  # Utils
  logger: ^2.5.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  dart_date: ^1.4.0
  collection: ^1.18.0
  form_validator: ^2.1.1
  flutter_isolate: ^2.1.0
  multi_value_listenable_builder: ^0.0.2
  tuple: ^2.0.2
  custom_rating_bar: ^3.0.0
  flutter_debouncer: ^2.0.0

  # File Picker
  file_picker: ^9.0.2

  # Slider
  sliding_up_panel: ^2.0.0+1

  # Theme
  flex_color_scheme: ^8.0.1

  # Svg
  flutter_svg: ^2.0.16

  # Socket
  socket_io_client: ^3.0.2
  web_socket_channel: ^3.0.1
  web_socket: ^0.1.6

  #Update and test
  shorebird_code_push: ^2.0.2

  #Pin
  pinput: ^5.0.0

  #Image
  cached_network_image: ^3.4.1

  #Fonts
  google_fonts: ^6.2.1

  # Icons
  iconsax_flutter: ^1.0.0
  hugeicons: ^0.0.11
  icons_plus: ^5.0.0

  # Serialization
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5

  # Dio
  dio: ^5.8.0+1
  dio_cache_interceptor: ^4.0.3

  # Internet Connection
  internet_connection_checker: ^3.0.1

  # Location
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  glassmorphism: ^3.0.0
  dotted_border: ^2.1.0
  intl: ^0.19.0
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  mime: ^2.0.0

  # Camera
  camera: ^0.11.0+2

  # List
  grouped_list: ^6.0.0
  connectivity_plus: ^6.1.4

  # Bottom Navigation
  persistent_bottom_nav_bar_v2: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

  build_runner: ^2.4.15
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/keys/
    - assets/images/
    - assets/fonts/
    - assets/svgs/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 300

    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi_Complete/Fonts/TTF/Satoshi-Variable.ttf
          weight: 400
        - asset: assets/fonts/Satoshi_Complete/Fonts/TTF/Satoshi-VariableItalic.ttf
          weight: 400
          style: italic

    - family: FunnelDisplay
      fonts:
        - asset: assets/fonts/Funnel_Display/static/FunnelDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/Funnel_Display/static/FunnelDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/Funnel_Display/static/FunnelDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Funnel_Display/static/FunnelDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/Funnel_Display/static/FunnelDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Funnel_Display/static/FunnelDisplay-Light.ttf
          weight: 300

flutter_gen:
  output: lib/core/helper/
  line_length: 80

  integrations:
    flutter_svg: true
    lottie: true

  assets:
    enabled: true
