// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4XmEkIsz9n9FG_Qr1VkZOsxVJyWKjI8A',
    appId: '1:815611123624:android:8a6f3c6d80f771a8266f9d',
    messagingSenderId: '815611123624',
    projectId: 'swappid-261c6',
    databaseURL: 'https://swappid-261c6-default-rtdb.firebaseio.com',
    storageBucket: 'swappid-261c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEO3ie81kV3M3t12jzZIRWEvCAswMFSno',
    appId: '1:815611123624:ios:0b213f5fcde2b8ac266f9d',
    messagingSenderId: '815611123624',
    projectId: 'swappid-261c6',
    databaseURL: 'https://swappid-261c6-default-rtdb.firebaseio.com',
    storageBucket: 'swappid-261c6.appspot.com',
    iosClientId:
        '815611123624-73k960h372qnba8c8id065k3i617jvq1.apps.googleusercontent.com',
    iosBundleId: 'com.company.useswappid',
  );
}
